#!/usr/bin/env python3
"""
Download boost.org Accumulators Reference HTML and emit reference.adoc with the same
fragment IDs as official ``reference.html`` (for User's Guide class name xrefs).

Requires: pip install beautifulsoup4
"""

from __future__ import annotations

import argparse
import html
import re
import sys
import urllib.request
from pathlib import Path

try:
    from bs4 import BeautifulSoup, NavigableString, Tag
except ImportError:
    print("Install beautifulsoup4: pip install beautifulsoup4", file=sys.stderr)
    sys.exit(1)

URL = "https://www.boost.org/doc/libs/latest/doc/html/accumulators/reference.html"


def _escape_adoc(s: str) -> str:
    return s.replace("\\", "\\\\").replace("[", "\\[")


def _convert_inline(el: Tag) -> str:
    parts: list[str] = []
    for child in el.children:
        if isinstance(child, NavigableString):
            parts.append(_escape_adoc(html.unescape(str(child))))
            continue
        if not isinstance(child, Tag):
            continue
        name = child.name.lower()
        if name == "a":
            href = child.get("href") or ""
            inner = "".join(
                _convert_inline(child)
                if isinstance(c, Tag)
                else _escape_adoc(html.unescape(str(c)))
                for c in child.children
            )
            m = re.match(
                r"(?:https?://[^/]+)?(?:/doc/libs/latest)?/doc/html/accumulators/reference\.html#(.+)",
                href,
            )
            frag = m.group(1) if m else ""
            if frag:
                inner_l = inner.replace("]", "\\]")
                return f"xref:reference.adoc#{frag}[{inner_l}]"
            if href.startswith("http"):
                return f"link:{href}[{inner}]"
            return inner
        if name in ("strong", "b"):
            t = "".join(
                _convert_inline(child)
                if isinstance(c, Tag)
                else _escape_adoc(html.unescape(str(c)))
                for c in child.children
            )
            return f"*{t}*"
        if name in ("em", "i"):
            t = "".join(
                _convert_inline(child)
                if isinstance(c, Tag)
                else _escape_adoc(html.unescape(str(c)))
                for c in child.children
            )
            return f"_{t}_"
        if name == "code":
            t = "".join(str(c) for c in child.children)
            return f"`{html.unescape(t)}`"
        if name == "br":
            return " +\n"
        parts.append(_convert_inline(child))
    return "".join(parts)


def _emit_pre(pre: Tag) -> str:
    raw = pre.get_text()
    return f"[source,c++]\n----\n{raw.rstrip()}\n----\n\n"


def _section_depth_from_tag(tag_name: str) -> int | None:
    """Return 0-based depth under the page title (h3 → 0 → AsciiDoc ``==``)."""
    if tag_name == "h3":
        return 0
    if tag_name == "h4":
        return 1
    if tag_name == "h5":
        return 2
    if tag_name == "h6":
        return 3
    return None


def convert_reference_ordered(soup: BeautifulSoup) -> str:
    """Use the inner legacy <body> and emit h* / pre in document order."""
    bodies = soup.find_all("body")
    inner = bodies[-1] if bodies else soup
    flow = inner.find_all(["h3", "h4", "h5", "h6", "pre"])

    started = False
    out: list[str] = [
        "= Reference\n",
        ":page-toclevels: 3\n\n",
        "// Autogenerated by tools/import_reference_from_official.py — do not edit.\n\n",
    ]

    for el in flow:
        if isinstance(el, NavigableString):
            continue
        if el.name in ("h3", "h4", "h5", "h6"):
            tp = el.find_parent("div", class_="titlepage")
            if tp is None:
                continue
            lev = _section_depth_from_tag(el.name)
            if lev is None:
                continue
            hashes = "=" * min(lev + 2, 6)  # lev=0 → ``==``
            a = el.find("a", attrs={"name": True})
            nm = (a.get("name") or "").strip() if a else ""
            if nm == "accumulators_framework_reference":
                started = True
            if not started:
                continue
            title_text = re.sub(r"\s+", " ", el.get_text(" ", strip=True))
            if nm:
                out.append(f"[[{_escape_adoc(nm)}]]\n")
            out.append(f"{hashes} {_escape_adoc(title_text)}\n\n")
            continue

        if el.name == "pre":
            if not started:
                continue
            # Skip tiny snippets outside synopsis if needed
            out.append(_emit_pre(el))

    return "".join(out)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", default=URL)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()
    html_text = urllib.request.urlopen(args.url, timeout=120).read().decode("utf-8", "replace")
    soup = BeautifulSoup(html_text, "html.parser")
    adoc = convert_reference_ordered(soup)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(adoc, encoding="utf-8")
    print(f"Wrote {args.out} ({len(adoc)} bytes)")


if __name__ == "__main__":
    main()
