////
Copyright Eric Niebler 2005.
Distributed under the Boost Software License, Version 1.0.
////

= Chapter 1. Boost.Accumulators
Eric Niebler

Copyright (C) 2005, 2006 Eric Niebler

Distributed under the Boost Software License, Version 1.0.
(See accompanying file LICENSE_1_0.txt or copy at
link:https://www.boost.org/LICENSE_1_0.txt[https://www.boost.org/LICENSE_1_0.txt])

:idprefix:
:sectanchors:
:toclevels: 2
:toc: left
:pagelevels: 1
:source-language: c++
:stem: latexmath

include::definitions.adoc[]

[#preface,pagelevels=0]
== Preface

[quote]
____
++"++It is better to be approximately right than exactly wrong.++"++

-- _Old adage_
____

=== Description

Boost.Accumulators is both a library for incremental statistical computation as
well as an extensible framework for incremental calculation in general. The library
deals primarily with the concept of an _accumulator_, which is a primitive
computational entity that accepts data one sample at a time and maintains some
internal state. These accumulators may offload some of their computations on other
accumulators, on which they depend. Accumulators are grouped within an
_accumulator set_. Boost.Accumulators resolves the inter-dependencies
between accumulators in a set and ensures that accumulators are processed in the
proper order.

:leveloffset: +1

include::user_s_guide.adoc[]

[#the_statistical_accumulators_library,pagelevels=1]
= The Statistical Accumulators Library

include::the_statistical_accumulators_library.adoc[]

include::acknowledgements.adoc[]

include::reference.adoc[]

include::ref/accumulators_framework_reference.adoc[]

include::ref/statistics_library_reference.adoc[]

include::ref/numeric_operators_library_reference.adoc[]

:leveloffset: -1
